## NumPY Array Operaton

In [2]:
import numpy as np

### Indexing & Slicing

In [5]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Basic Slicing: {array[2:7]}")
print(f"With steps: {array[2:8:2]}")
print(f"Negative Indexing: {array[-3]}")


Basic Slicing: [3 4 5 6 7]
With steps: [3 5 7]
Negative Indexing: 7


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(f"Specific Element: {arr_2d[2, 1]}")
print(f"Specific Element: {arr_2d[2][1]}")
print(f"Entire row: {arr_2d[2]}")
print(f"Entire column: {arr_2d[:, 2]}") # colon means all rows and after comma we have specify to show which column

Specific Element: 8
Specific Element: 8
Entire row: [7 8 9]
Entire column: [3 6 9]


### Sorting

In [11]:
unsorted = np.array([3, 4, 5, 1, 3, 9, 6])
sorted = np.sort(unsorted)
print(f"Sorted Array: {sorted}")

Sorted Array: [1 3 3 4 5 6 9]


In [ ]:
arr_2d_unsorted = np.array([[3, 1],
                            [7, 2],
                            [8, 0]])
print(f"Sorted 2d Array by column:\n {np.sort(arr_2d_unsorted, axis = 0)}\n")
print(f"Sorted 2d Array by row:\n {np.sort(arr_2d_unsorted, axis = 1)}\n")


Sorted 2d Array by column:
 [[3 0]
 [7 1]
 [8 2]]

Sorted 2d Array by row:
 [[1 3]
 [2 7]
 [0 8]]



### Filter

In [15]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ])
even_num = numbers[numbers % 2 == 0]
print(f"Even Numbers: {even_num}")
odd_num = numbers[numbers % 2 != 0]
print(f"Odd Numbers: {odd_num}")

Even Numbers: [ 2  4  6  8 10]
Odd Numbers: [1 3 5 7 9]


In [17]:
# Filter with mask
mask = numbers > 5
print(f"Numbers greater than 5: {numbers[mask]}")

Numbers greater than 5: [ 6  7  8  9 10]


#### Fancy Indexing vs np.where

In [24]:
indices = [1, 2, 5]
print(f"{numbers[indices]}")

where_result = np.where(numbers > 5)
print(where_result) # print only indices
print(f"Where Result: {numbers[where_result]}")

condition_array = np.where(numbers > 5, numbers *2, numbers)
condition_array1 = np.where(numbers > 5, numbers, numbers)
condition_array2 = np.where(numbers > 5, "true", "false")
print(condition_array)
print(condition_array1)
print(condition_array2)

[2 3 6]
(array([5, 6, 7, 8, 9]),)
Where Result: [ 6  7  8  9 10]
[ 1  2  3  4  5 12 14 16 18 20]
[ 1  2  3  4  5  6  7  8  9 10]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and Removing data

In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = arr1 + arr2
print(combined)

combined = np.concatenate((arr1, arr2))
print(f"Concatenation: {combined}")

#In NumPy, arrays have a fixed size in memory. That means operations
# like "adding" or "removing" elements don't actually modify the 
# original array in place—instead, they return a new array with the changes applied.
arr = np.array([10, 20, 30])
new_arr = np.append(arr, [40, 50])
print("Adding Elements in the Array: ", new_arr)

matrix = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
matrix_with_row = np.append(matrix, new_row, axis=0)
print("Adding Entire Row:\n ", matrix_with_row, "\n")

arr = np.array([10, 20, 40, 50])

# Insert 30 at index 2
new_arr = np.insert(arr, 2, 30)
print("Insertion of 30 at index 2: ",new_arr, "\n") 
# Output: [10 20 30 40 50]

# Insert multiple elements at index 1
new_arr_multi = np.insert(arr, 1, [12, 15])
print("Inserting multiple elements at index 1: ", new_arr_multi, "\n") 
# Output: [10 12 15 20 40 50]


# Removing
arr = np.array([10, 20, 30, 40, 50])

# Delete element at index 1 (value 20)
arr_after_del = np.delete(arr, 1)
print(f"Deleting Specific value: {arr_after_del}\n") 
# Output: [10 30 40 50]

# Delete multiple indices (indices 0 and 3)
arr_multi_del = np.delete(arr, [0, 3])
print(f"Deleting multiple values: {arr_multi_del}\n") 
# Output: [20 30 50]

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Delete the 2nd column (index 1, axis=1)
no_col1 = np.delete(matrix, 1, axis=1)
print(f"Deleting Entire column: \n{no_col1}\n")
no_col2 = np.delete(matrix, 1, axis=0)
print(f"Deleting Entire row: \n{no_col2}\n")


[5 7 9]
Concatenation: [1 2 3 4 5 6]
Adding Elements in the Array:  [10 20 30 40 50]
Adding Entire Row:
  [[1 2]
 [3 4]
 [5 6]] 

Insertion of 30 at index 2:  [10 20 30 40 50] 

Inserting multiple elements at index 1:  [10 12 15 20 40 50] 

Deleting Specific value: [10 30 40 50]

Deleting multiple values: [20 30 50]

Deleting Entire column: 
[[1 3]
 [4 6]
 [7 9]]

Deleting Entire row: 
[[1 2 3]
 [7 8 9]]



### Array Compatibility

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 8])

print(f"Compatibility Shapes: {a.shape == b.shape}")

Compatibility Shapes: True


In [40]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(f"Original Array: \n{original}\n")
print(f"With new Row: \n{with_new_row}\n")

new_col = np.array([[5], [6]])
with_new_col = np.hstack((original, new_col))
print(f"With new Column: \n{with_new_col}")


Original Array: 
[[1 2]
 [3 4]]

With new Row: 
[[1 2]
 [3 4]
 [5 6]]

With new Column: 
[[1 2 5]
 [3 4 6]]


### Split

In [41]:
arr = np.array([10, 20, 30, 40, 50, 60])

# Split into 3 equal arrays
result = np.split(arr, 3)
print(f"Splitting of Array: \n{result}")

Splitting of Array: 
[array([10, 20]), array([30, 40]), array([50, 60])]


In [42]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split at index 2 and index 6:
# Part 1: [:2]      -> [1, 2]
# Part 2: [2:6]     -> [3, 4, 5, 6]
# Part 3: [6:]      -> [7, 8, 9]
result = np.split(x, [2, 6])

print(f"Splitting at specific indices: \n{result}")

Splitting at specific indices: 
[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


In [43]:
arr = np.array([1, 2, 3, 4, 5])

# Split 5 elements into 3 sub-arrays
result = np.array_split(arr, 3)

print(f"Unequal Splitting: \n{result}")


Unequal Splitting: 
[array([1, 2]), array([3, 4]), array([5])]


In [ ]:
# Vertical Split
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
top, bottom = np.vsplit(matrix, 2)

print(top)    
print(bottom)

[[1 2 3 4]]
[[5 6 7 8]]


In [51]:
# Horizontal Split
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
left, right = np.hsplit(matrix, 2)

print("left = \n", left, "\n")
print("right = \n", right, "\n")

left, right, a, b = np.hsplit(matrix, 4)
print("left = \n", left, "\n")
print("right = \n", right, "\n")
print("a= \n", a, "\n")
print("b= \n", b, "\n")


left = 
 [[1 2]
 [5 6]] 

right = 
 [[3 4]
 [7 8]] 

left = 
 [[1]
 [5]] 

right = 
 [[2]
 [6]] 

a= 
 [[3]
 [7]] 

b= 
 [[4]
 [8]] 



### Challenge

In [3]:
# 1. Create the 3x3 matrix
matrix = np.arange(1, 10).reshape(3, 3)
print("Original Matrix:\n", matrix)
print("-" * 30)

# 2. Print requested elements/operations without loops

# First row
print("First row:", matrix[0])

# Last row
print("Last row:", matrix[-1])

# First column
print("First column:", matrix[:, 0])

# Last column
print("Last column:", matrix[:, -1])

# Main diagonal
print("Main diagonal:", np.diagonal(matrix))  # or matrix.diagonal()

# Reverse every row
print("Reverse every row:\n", matrix[:, ::-1])

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
First row: [1 2 3]
Last row: [7 8 9]
First column: [1 4 7]
Last column: [3 6 9]
Main diagonal: [1 5 9]
Reverse every row:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


### Project

In [4]:
# 1. Create marks array for 10 students
marks = np.array([78, 85, 91, 67, 88, 94, 72, 81, 69, 90])

# 2. Calculations
total_marks = np.sum(marks)
average_marks = np.mean(marks)
highest_marks = np.max(marks)
lowest_marks = np.min(marks)
std_dev = np.std(marks)
median_marks = np.median(marks)

# Print all calculated statistics
print(f"Total Marks: {total_marks}")
print(f"Average Marks: {average_marks:.2f}")
print(f"Highest Marks: {highest_marks}")
print(f"Lowest Marks: {lowest_marks}")
print(f"Standard Deviation: {std_dev:.2f}")
print(f"Median Marks: {median_marks}")

print("-" * 35)

# 3. Students Above Average (using Boolean Indexing)
above_average = marks[marks > average_marks]

print("Students Above Average:")
print(above_average)

Total Marks: 815
Average Marks: 81.50
Highest Marks: 94
Lowest Marks: 67
Standard Deviation: 9.18
Median Marks: 83.0
-----------------------------------
Students Above Average:
[85 91 88 94 90]
