## NumPY Array and Basics

In [1]:
import numpy as np 

### Creating Array

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr_1d}")

1D Array: [1 2 3 4 5]


In [6]:
arr_2d=np.array([[1, 2 ,3], [4, 5, 6]])
print(f"2D Array: {arr_2d}")

2D Array: [[1 2 3]
 [4 5 6]]


### List vs NumPY Array

In [12]:
py_list = [1, 2, 3, 4, 5]
print(f"Python List Multiplication: {py_list * 2}")

np_array = np.array([1, 2, 3, 4, 5])
print(f"Numpy Array Multiplication: {np_array * 2}")

import time
start = time.time()
py_list = [ i*2 for i in range(1000000)]
print(f"Python List Time: {time.time() - start}")


start = time.time()
np_array = np.arange(0, 1000000) * 2
print(f"Numpy Array Time: {time.time() - start}")


Python List Multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array Multiplication: [ 2  4  6  8 10]
Python List Time: 0.10750985145568848
Numpy Array Time: 0.008264541625976562


### Creating Array from scratch

In [24]:
zeros = np.zeros((3, 4), dtype=int)
print(f"zero array:\n{zeros}\n")

ones = np.ones((3, 4), dtype=int)
print(f"ones array:\n{ones}\n")

full = np.full((4, 4), 6, dtype = int)
print(f"full array:\n{full}\n")

random = np.random.random((3, 5))
print(f"random array:\n{random}\n")

# 0 se 100 ke beech random integers create karne ke liye:
random = np.random.randint(0, 100, size=(3, 5))
print(f"random whole nmbr array:\n{random}\n")

sequence = np.arange(0, 20, 2)
print(f"random whole nmbr array:{sequence}\n")

zero array:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

ones array:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

full array:
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]

random array:
[[0.30451194 0.8422934  0.32054348 0.4406371  0.90473693]
 [0.73949277 0.17070702 0.65155641 0.33625795 0.14208289]
 [0.90928511 0.63277399 0.59032104 0.02546117 0.88632043]]

random whole nmbr array:
[[82 39 77 55 47]
 [82 65 65 56 36]
 [60 10  5 80 11]]

random whole nmbr array:[ 0  2  4  6  8 10 12 14 16 18]



### Vector Matrix Tensor

In [29]:
vector = np.array([1, 2, 3, 4, 5])
print(f"Vector: {vector}\n")

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Matrix:\n {matrix}\n")

tensor = np.array([[[1, 2], [3, 4], [9, 10]],
                   [[5, 6], [7, 8], [11, 12]]])
print(f"Tensor: \n{tensor}\n")
print(f"Tensor Shape: \n{tensor.shape}\n")
print(f"Tensor Dimension: \n{tensor.ndim}\n")


Vector: [1 2 3 4 5]

Matrix:
 [[1 2 3]
 [4 5 6]]

Tensor: 
[[[ 1  2]
  [ 3  4]
  [ 9 10]]

 [[ 5  6]
  [ 7  8]
  [11 12]]]

Tensor Shape: 
(2, 3, 2)

Tensor Dimension: 
3



### Array Properties

In [32]:
array = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(f"Shape: {array.shape}\n")
print(f"Dimension: {array.ndim}\n")
print(f"Size: {array.size}\n")
print(f"Dtype: {array.dtype}\n")
print(f"Item size: {array.itemsize}\n")
print(f"Total Memory: {array.nbytes}\n")

Shape: (2, 3)

Dimension: 2

Size: 6

Dtype: int64

Item size: 8

Total Memory: 48



### Array Reshaping

In [ ]:
# Array Reshaping
arr = np.arange(12)
print(f"Original Array: {arr}\n")

reshaped = arr.reshape(3, 4)
print(f"Reshaped Array: \n{reshaped}\n")

flattened = reshaped.flatten()
print(f"Flattened Array: \n{flattened}\n")

# revel(return view instead of copy)
raveled = reshaped.ravel()
print(f"Raveled Array: \n{raveled}\n")

transposed = reshaped.T
print(f"Transposed Array: \n{transposed}\n")

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled Array: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed Array: 
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]



### Practice

In [2]:
a= np.array([1, 2, 3, 4, 5, 6])
print(a)
b = a[: 3]
print(b)
c = a[3: ]
print(c)

[1 2 3 4 5 6]
[1 2 3]
[4 5 6]


In [7]:
arr = np.empty((2), dtype=np.int8)
print(f"Empty Array: \n{arr}\n")

Empty Array: 
[-80  64]



In [10]:
arr = np.linspace(0, 25, 5)
print(arr)

[ 0.    6.25 12.5  18.75 25.  ]


In [14]:
import numpy as np

# Target array MUST be sorted
arr = np.array([10, 20, 30, 40, 50])
values_to_insert = np.array([25, 5, 40])

# Find insertion indices
indices = np.searchsorted(arr, values_to_insert)

print("Insertion indices:", indices)
print(arr[indices])
# Output: [2 0 3]
# - 25 goes at index 2 (between 20 and 30)
# - 5 goes at index 0 (before 10)
# - 40 goes at index 3 (left side of existing 40)

Insertion indices: [2 0 3]
[30 10 40]


In [17]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
arr = np.concatenate((x, y))
print(arr)

[[1 2]
 [3 4]
 [5 6]]


### Coverting 1D Array into 2D Array

In [18]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [20]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

### Indexing and Slicing

In [24]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[: 2])
print(data[-2:])

2
[1 2]
[2 3]
[1 2]
[2 3]


In [29]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print(a[a < 5])
five_up = (a >= 5)
print(a[five_up])
divisible_by_2 = a[a%2==0]
print(divisible_by_2)
print([a < 5])

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])]


In [ ]:
b = np.nonzero(a > 5)
print(b)
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)
# it returns oonly indices of true values which satisfy the condition like in this example all elements whose idnex is greater than 5 

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))
(np.int64(1), np.int64(1))
(np.int64(1), np.int64(2))
(np.int64(1), np.int64(3))
(np.int64(2), np.int64(0))
(np.int64(2), np.int64(1))
(np.int64(2), np.int64(2))
(np.int64(2), np.int64(3))


### Practice Questions

In [ ]:
# Q1 Create an array containing numbers from 1 to 10.
a = np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [39]:
# Q2 Create an array of five zeros.
zeros = np.zeros([5], dtype=int)
print(f"Zeros Array: {zeros}")


Zeros Array: [0 0 0 0 0]


In [40]:
# Q3 Create an array of five zeros.
ones = np.ones([5], dtype=int)
print(f"Ones Array: {ones}")

Ones Array: [1 1 1 1 1]


In [41]:
# Q4 Create an array from 10 to 50.
array = np.arange(10, 51)
print(f"Array from 10 to 50: \n{array}")

Array from 10 to 50: 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [43]:
# Q5 Print: Shape, Number of dimensions, Data type of the array.
print(f"Array Shape: {array.shape}")
print(f"Array Dimension: {array.ndim}")
print(f"Array Dtype: {array.dtype}")

Array Shape: (41,)
Array Dimension: 1
Array Dtype: int64


In [46]:
# Q6 Print: First element, Last element, Third element
print(f"First Element: {array[0]}")
print(f"Last Element: {array[-1]}")
print(f"Third Element: {array[2]}")

First Element: 10
Last Element: 50
Third Element: 12


In [48]:
# Q7 Slice the array. Print: First five elements, Last five elements, Middle elements
print(f"First Five Element: {array[: 5]}")
print(f"Last Five Element: {array[-5 :]}")
print(f"Middle Elements: {array[5 : -5]}")

First Five Element: [10 11 12 13 14]
Last Five Element: [46 47 48 49 50]
Middle Elements: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45]


In [49]:
# Q8 Change the third element to 100.
array[2] = 100
print(f"Updated Array: {array}")

Updated Array: [ 10  11 100  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50]


In [55]:
# Q9 Create a 3×3 array. and print second row third column
array = ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"3x3 Array: \n {array}")
print(f"Second row, third column: {array[1][2]}")


3x3 Array: 
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Second row, third column: 6


In [ ]:
# Q10 Create this matrix:
# 0 1 2
# 3 4 5
# 6 7 8
#Print only: 4 using indexing.

matrix = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

# Row index 1 (2nd row), Column index 1 (2nd column) -> Element '4'
print(matrix[1, 1])

In [58]:
# Mini Project
marks = np.array([78, 85, 92, 67, 88])
print(f"Marks: {marks}")
print(f"Highest Marks: {np.max(marks)}")
print(f"Lowest Marks: {np.min(marks)}")
print(f"Average Marks: {np.mean(marks)}")
print(f"Total Marks: {np.sum(marks)}")



Marks: [78 85 92 67 88]
Highest Marks: 92
Lowest Marks: 67
Average Marks: 82.0
Total Marks: 410
