## Advance Operation with Business Examples

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Data Structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], # Paradise Biryani
    [2, 120000, 140000, 160000, 190000], # Beijing Bites
    [3, 200000, 230000, 260000, 300000], # Pizza Hub
    [4, 180000, 210000, 240000, 270000], # Burger Point
    [5, 160000, 185000, 205000, 230000], # Chai Point
])

print("==== Sales Analysis ====")
print("\n Sales data shape", sales_data.shape)
print("\n Sample data for 1st 3 restaurant: \n", sales_data[:3])


==== Sales Analysis ====

 Sales data shape (5, 5)

 Sample data for 1st 3 restaurant: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [6]:
# total sales per year
print(np.sum(sales_data, axis = 0))
# yearly total
yearly_total = np.sum(sales_data[:, 1:], axis = 0)
print(yearly_total)

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
